const EventMockData = [
  {
    key: 1,
    img: '/imgs/1.jpg',
    category: 'WIE',
    title: 'Introduction to Blockchain',
    status: 'ongoing',
    more: '',
  },
  {
    key: 2,
    img: '/imgs/2.jpg',
    category: 'CS',
    title: 'Competitive Programming',
    status: 'upcoming',
    more: '',
  },
  {
    key: 3,
    img: '/imgs/3.jpg',
    category: 'SB',
    title: 'ML AI Random Title',
    status: 'upcoming',
    more: '',
  },
  {
    key: 4,
    img: '/imgs/4.jpg',
    category: 'SB',
    title: 'Web Scrapping',
    status: 'upcoming',
    more: '',
  },
  {
    key: 5,
    img: '/imgs/3.jpg',
    category: 'WIE',
    title: 'Cybersecurity',
    status: 'upcoming',
    more: '',
  },
  {
    key: 6,
    img: '/imgs/2.jpg',
    category: 'SB',
    title: 'Unity Development',
    status: 'upcoming',
    more: '',
  },
  {
    key: 7,
    img: '/imgs/1.jpg',
    category: 'WIE',
    title: 'MERN vs MEAN vs MEVN',
    status: 'upcoming',
    more: '',
  },
  {
    key: 8,
    img: '/imgs/2.jpg',
    category: 'CS',
    status: 'upcoming',
    title: 'Random Topics',
    more: '',
  },
];
export default EventMockData;
