const Sdata = [
    {
        key: 1,
        img: "https://picsum.photos/400/300",
        category: "IEEE WIE MUJ",
        title: "Bitcoin",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 2,
        img: "./imgs/2.jpg",
        category: "IEEE CS MUJ",
        title: "Competetive Progamming",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 3,
        img: "",
        category: "IEEE SB MUJ",
        title: "ML AI",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 4,
        img: "",
        category: "IEEE SB MUJ",
        title: "Web Scrapping",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 5,
        img: "",
        category: "IEEE WIE MUJ",
        title: "Cybersecurity",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 6,
        img: "",
        category: "IEEE SB MUJ",
        title: "Unity Development",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 7,
        img: "",
        category: "IEEE WIE MUJ",
        title: "MERN vs MEAN vs MEVN",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
    {
        key: 8,
        img: "",
        category: "IEEE cs MUJ",
        title: "Random Topics",
         desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        more: "",
    },
];
export default Sdata;